pusher: &pusher
  adapter_javascript_url: "http://js.pusher.com/2.0/pusher.min.js" 
  app_id: "42844"
  api_key: "210725a706de9be7ec90"
  auth_token: "b31852615d9168411e2f"
  adapter: "Pusher"

development:
  <<: *pusher
  async: false

test:
  <<: *pusher
  async: false

production:
  <<: *pusher
  async: true